spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:booking_db}
spring.datasource.username=${DB_USER:booking}
spring.datasource.password=${DB_PASSWORD:booking_pass}


jwt.secret=${JWT_SECRET}

spring.ai.openai.api-key=${OPENAI_API_KEY}

