spring.application.name=booking.backend
spring.profiles.active=dev
server.port=${PORT:8080}
app.time-zone=${APP_TIME_ZONE:America/Montevideo}

spring.jpa.hibernate.ddl-auto=validate


jwt.expiration-ms=3600000


spring.ai.openai.chat.model=gpt-6-sol
spring.ai.openai.chat.reasoning-effort=none
